name: temulapak_app
description: "TemuLapak, a platform for street vendor and buyer."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.7
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  geolocator: ^13.0.4
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/animation/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter_Regular.ttf
        - asset: lib/assets/fonts/Inter_SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter_Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Inter_Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Inter_Bold.ttf
          weight: 700
