name: temulapak_app
description: "TemuLapak, a platform for street vendor and buyer."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/animation/
